services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: K21032208k
      POSTGRES_DB: trabalho
    ports:
      - "5432:5432"  
    volumes:
      - pgdata:/var/lib/postgresql/data 
volumes:
  pgdata:
